export enum RoleEnum {
    SUPER_ADMINISTRATOR = 1,
    ADMINISTRATOR = 2,
    DIREKTOR = 3,
    KOORDINATOR = 4,
    PROFESOR = 5,
    MENTOR = 6,
    ODELJENSKI_STARESINA = 7,
    UCENIK = 8,
    PREDSEDNIK_KOMISIJE = 9,
    RUKOVODILAC_AKTIVA = 10,
}
export enum TopicStatusEnum {
    SLOBODNA = 1,
    NA_CEKANJU = 2,
    REZERVISANA = 3,
}
export enum ClassEnum {
    DRUSTVENO_JEZICKI = 1,
    PRIRODNO_MATEMATICKI = 2,
    UCENICI_SA_POSEBNIM_SPOSOBNOSTIMA_ZA_INFORMATIKU = 3,
    UCENICI_SA_POSEBNIM_SPOSOBNOSTIMA_ZA_FIZIKU = 4,
}
export enum StudentEnum {
    AKTIVAN = 1,
    ARHIVIRAN = 2,
}
export enum GraduationPaperEnum {
    POSLAT = 1,
    NA_PREGLEDANJU = 2,
    POTREBNO_KORIGOVANJE = 3,
    ODOBREN_ZA_STAMPU = 4,
}