namespace api.Enums
{
    public enum ClassEnum
    {
        DRUSTVENO_JEZICKI = 1,
        PRIRODNO_MATEMATICKI = 2,
        UCENICI_SA_POSEBNIM_SPOSOBNOSTIMA_ZA_INFORMATIKU = 3,
        UCENICI_SA_POSEBNIM_SPOSOBNOSTIMA_ZA_FIZIKU = 4
    }
}