services:
  app:
    build: .
    container_name: app
    environment:
      - MONGO_URI_PUBLIC=${MONGO_URI_PUBLIC}
      - MONGO_URI_PRIVATE=${MONGO_URI_PRIVATE}
      - CLIENT_URL=${CLIENT_URL}
      - PORT=${PORT}
    networks:
      - app-network
    depends_on:
      - mongo
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
volumes:
  mongo_data:
networks:
  app-network:
    driver: bridge