version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Redis__ConnectionString=redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"